services:
  db:
    image: postgres:latest
    container_name: db_users
    restart: always
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env-non-dev
    volumes:
      - .db:/var/lib/postgresql/data
    command: -p 1221
    expose:
      - 1221
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ssh: 
      - default
    env_file:
      - .env-non-dev
    container_name: rsp_api
    command: ["/RSP/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
volumes:
  db:
    driver: local

