services:
  db:
    image: postgres:14.1-alpine
    container_name: db_users
    restart: always
    env_file:
      - .env-non-dev
    
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge