services:
  db:
    image: postgres:15
    container_name: db_users
    env_file:
      - .env-non-dev
    command: -p 1221
    expose:
      - 1221
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ssh: 
      - default
    env_file:
      - .env-non-dev
    container_name: rsp_api
    command: ["/RSP/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
    