version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_users
    env_file:
      - .env-non-dev
  app:
    build:
      context: .
      dockerfile: Dockerfile
      ssh: 
      - default
    env_file:
      - .env-non-dev
    container_name: rsp_api
    command: ["/RSP/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
    