"""fix acces token

Revision ID: 2c0fb7d7cb3d
Revises: 2f6d1701d18e
Create Date: 2024-09-05 21:26:39.727835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0fb7d7cb3d'
down_revision: Union[str, None] = '2f6d1701d18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accesstoken', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accesstoken', 'created_at')
    # ### end Alembic commands ###
