"""add register_at, name no uniq

Revision ID: 76e88a579c57
Revises: 5976af395346
Create Date: 2024-09-30 18:57:13.714169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e88a579c57'
down_revision: Union[str, None] = '5976af395346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_at', sa.TIMESTAMP(), nullable=True))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'registered_at')
    # ### end Alembic commands ###
